package com.sch.order_rules.fact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "\u8BA2\u5355\u539F\u4EF7\u91D1\u989D")
    private java.lang.Integer amout;
    @org.kie.api.definition.type.Label(value = "\u79EF\u5206")
    private java.lang.Integer score;

    public Order() {
    }

    public java.lang.Integer getAmout() {
        return this.amout;
    }

    public void setAmout(java.lang.Integer amout) {
        this.amout = amout;
    }

    public java.lang.Integer getScore() {
        return this.score;
    }

    public void setScore(java.lang.Integer score) {
        this.score = score;
    }

    public Order(java.lang.Integer amout, java.lang.Integer score) {
        this.amout = amout;
        this.score = score;
    }

}
