package com.sch.order_rules.fact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("订单原价金额")
    private java.lang.Integer amout;
    @org.kie.api.definition.type.Label("积分")
    private java.lang.Integer score;

    @org.kie.api.definition.type.Label(value = "\u63CF\u8FF0")
    private java.lang.String info;

    public Order() {
    }

    public java.lang.Integer getAmout() {
        return this.amout;
    }

    public void setAmout(java.lang.Integer amout) {
        this.amout = amout;
    }

    public java.lang.Integer getScore() {
        return this.score;
    }

    public void setScore(java.lang.Integer score) {
        this.score = score;
    }

    public java.lang.String getInfo() {
        return this.info;
    }

    public void setInfo(java.lang.String info) {
        this.info = info;
    }

    public Order(java.lang.Integer amout, java.lang.Integer score,
                 java.lang.String info) {
        this.amout = amout;
        this.score = score;
        this.info = info;
    }

}
