package com.myspace.test.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dog implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String name;
    private int age;

    public Dog() {
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Dog(java.lang.String name, int age) {
        this.name = name;
        this.age = age;
    }

}
